# -*- coding: utf-8 -*-
"""
Asset Register XLSX Export
==========================

Uses centralized OPSExcelStyles for consistent branding.
v19.0.2.5: Phase 5 - Applied corporate branding via excel_styles.
"""

from odoo import models
from datetime import datetime
from .excel_styles import OPSExcelStyles, apply_standard_widths


class AssetRegisterXLSX(models.AbstractModel):
    """
    This model generates an XLSX report for the asset register, providing a detailed
    overview of all company assets, their valuation, depreciation, and status.
    It inherits from 'report.report_xlsx.abstract' to leverage Odoo's XLSX reporting
    capabilities.
    """
    _name = 'report.ops_matrix_accounting.report_asset_register_xlsx'
    _inherit = 'report.report_xlsx.abstract'
    _description = 'Asset Register XLSX Report'

    def generate_xlsx_report(self, workbook, data, assets):
        """
        Generates the XLSX report content.

        Args:
            workbook: The XLSX workbook object.
            data (dict): Data passed from the wizard or report action.
            assets (recordset): The 'ops.asset' recordset to be reported on.
        """
        # Initialize centralized styles
        styles = OPSExcelStyles(workbook)

        sheet = workbook.add_worksheet('Asset Register')

        # Apply standard column widths
        apply_standard_widths(sheet, [
            'name',       # Asset Name (35)
            'code',       # Asset Code (15)
            'name_short', # Category (25)
            'date',       # Purchase Date (12)
            'currency',   # Purchase Value (15)
            'datetime',   # Depreciation Start Date (18)
            'currency',   # Book Value (15)
            'status'      # Status (12)
        ])

        # Report Title
        sheet.merge_range('A1:H1', 'ASSET REGISTER REPORT', styles.title)
        sheet.set_row(0, 30)  # Increase title row height

        # Metadata section
        row = 1
        sheet.write(row, 0, 'Generated:', styles.meta_label)
        sheet.write(row, 1, datetime.now().strftime('%Y-%m-%d %H:%M:%S'), styles.meta_value)
        row += 1

        sheet.write(row, 0, 'Total Assets:', styles.meta_label)
        sheet.write(row, 1, len(assets), styles.meta_value)
        row += 2

        # Table Headers
        headers = [
            'Asset Name', 'Asset Code', 'Category', 'Purchase Date',
            'Purchase Value', 'Depreciation Start', 'Book Value', 'Status'
        ]
        for col_num, header in enumerate(headers):
            sheet.write(row, col_num, header, styles.header)
        row += 1

        # Status to badge mapping
        status_badges = {
            'draft': styles.badge_info,
            'active': styles.badge_success,
            'fully_depreciated': styles.badge_warning,
            'disposed': styles.badge_muted,
            'sold': styles.badge_muted,
        }

        # Data Rows with zebra striping
        total_purchase_value = 0.0
        total_book_value = 0.0

        for idx, asset in enumerate(assets):
            state_label = dict(asset._fields['state'].selection).get(asset.state, '')

            # Get zebra-striped styles
            text_style = styles.get_row_style(idx, is_currency=False)
            currency_style = styles.get_row_style(idx, is_currency=True)
            status_style = status_badges.get(asset.state, styles.badge_muted)

            sheet.write(row, 0, asset.name or '', text_style)
            sheet.write(row, 1, asset.code or '', text_style)
            sheet.write(row, 2, asset.category_id.name or '', text_style)
            sheet.write(row, 3, asset.purchase_date, styles.date)
            sheet.write(row, 4, asset.purchase_value, currency_style)
            sheet.write(row, 5, asset.depreciation_start_date, styles.date)
            sheet.write(row, 6, asset.book_value, currency_style)
            sheet.write(row, 7, state_label, status_style)

            total_purchase_value += asset.purchase_value or 0.0
            total_book_value += asset.book_value or 0.0
            row += 1

        # Totals row
        sheet.write(row, 3, 'TOTALS:', styles.total)
        sheet.write(row, 4, total_purchase_value, styles.total_currency)
        sheet.write(row, 5, '', styles.total)
        sheet.write(row, 6, total_book_value, styles.total_currency)
        sheet.write(row, 7, '', styles.total)
        row += 2

        # Summary box
        sheet.write(row, 0, 'Total Depreciation:', styles.meta_label)
        sheet.write(row, 1, total_purchase_value - total_book_value, styles.currency)
        row += 1

        # Footer
        row += 1
        sheet.merge_range(
            row, 0, row, 7,
            'Generated by OPS Matrix | Asset data sourced from Fixed Asset Management module',
            styles.meta_value
        )
